-- CreateTable
CREATE TABLE `CaseCount` (
    `id` INTEGER NOT NULL AUTO_INCREMENT,
    `bachelor` INTEGER NOT NULL DEFAULT 0,
    `master` INTEGER NOT NULL DEFAULT 0,
    `phd` INTEGER NOT NULL DEFAULT 0,
    `internship` INTEGER NOT NULL DEFAULT 0,
    `postdoc` INTEGER NOT NULL DEFAULT 0,
    `created_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
    `updated_at` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),

    UNIQUE INDEX `CaseCount_id_key`(`id`),
    PRIMARY KEY (`id`)
) DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;
