-- AlterTable
ALTER TABLE `Home` ADD COLUMN `address` LONGTEXT NULL,
    ADD COLUMN `email` LONGTEXT NULL,
    ADD COLUMN `end_time` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `facebook` LONGTEXT NULL,
    ADD COLUMN `instagram` LONGTEXT NULL,
    ADD COLUMN `mobile` LONGTEXT NULL,
    ADD COLUMN `start_time` DATETIME(3) NULL DEFAULT CURRENT_TIMESTAMP(3),
    ADD COLUMN `twitter` LONGTEXT NULL;

-- AlterTable
ALTER TABLE `Testimonials` ADD COLUMN `program` LONGTEXT NULL,
    ADD COLUMN `scholarshipProgram` LONGTEXT NULL,
    ADD COLUMN `session` LONGTEXT NULL,
    ADD COLUMN `university` LONGTEXT NULL;
